In [1]:
#addition and subtraction requires equal number of values in matrices in same order
import numpy as np

In [2]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[7, 8, 9], [10, 11, 12]])

Addition of Matrices:

In [3]:
m1 + m2

array([[ 8, 10, 12],
       [14, 16, 18]])

Subtraction of Matrices:

In [4]:
m1 - m2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [5]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

Addition of Vectors:

In [6]:
v1 + v2

array([5, 7, 9])

Subtraction of Vectors:

In [7]:
v1 - v2

array([-3, -3, -3])